import BlogList from "./components/BlogList";
import ProfileBanner from "./components/ProfileBanner";
import ProfileCard from "./components/ProfileCard";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <section className="w-full mt-16 mb-6 flex gap-6 flex-col justify-center items-center">
        <ProfileBanner />
        <section className="w-full md:w-[78%] flex flex-col-reverse gap-3 md:gap-[1%] justify-center">
          <ProfileCard />
          <BlogList />
        </section>
      </section>
    </>
  );
}
