import "./globals.css";
import ReduxProvider from "./redux-store/ReduxProvider"; // Import Redux Provider

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-zinc-100">
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
