import MobileSettingsSidebar from "./components/MobileSettingsSidebar";
import Profile from "./components/Profile";
import SettingsSidebar from "./components/SettingsSidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <section className="mt-16 py-8 w-full flex items-center justify-center">
      <div className="w-full md:w-[80%] flex gap-4 mb-10">
        <SettingsSidebar />
        <MobileSettingsSidebar/>
        <Profile/>
      </div>
    </section>
  );
}
