import MobileDashboardSidebar from "./components/MobileDashboardSidebar";
import BlogSidebar from "./components/DashboardSidebar";
import BlogStats from "./components/BlogStats";
import MenuSection from "./components/MenuSection";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <section className="mt-16 py-4 md:p-6 h-fit w-full">
      <BlogStats />
      <section className="w-full mt-4 flex gap-4 mb-14">
        <BlogSidebar />
        <MobileDashboardSidebar/>
        <MenuSection />
      </section>
    </section>
  );
}
